version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: bun
    directory: /web/default
    schedule:
      interval: weekly
      day: tuesday
      time: '04:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: bun
    directory: /web/classic
    schedule:
      interval: weekly
      day: wednesday
      time: '04:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /electron
    schedule:
      interval: weekly
      day: thursday
      time: '04:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '04:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: '04:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
